---
spec/spec_helper.rb:
  hiera_config: "'spec/fixtures/hiera.yaml'"
  facterdb_string_keys: true
spec/spec_helper_acceptance.rb:
  unmanaged: false
.puppet-lint.rc:
  enabled_lint_checks:
    - parameter_documentation
    - parameter_types
